### ISSUE TITLE
port bakery module - set up on backdropcms.org + subdomains

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/forum.backdropcms.org#1]
we will need this to share sessions across www / api / forum

**Comment by docwilmot** [comment]
i will start this

**Comment by docwilmot** [comment]
Code up, full Backdropification, but no testing done.

**Comment by jenlampton** [comment]
It's alive!!!!!  https://backdropcms.org/project/bakery

**Comment by jenlampton** [comment]
bakery set up on forum site.

**Comment by jenlampton** [comment]
bakery set up on api site too.

**Comment by jenlampton** [comment]
bakery set up on localize.
