### ISSUE TITLE
Email people when activity happens on a forum topic

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/forum.backdropcms.org#10]
In order to keep people coming back to the forum, we'll need to be able to email them when someone replies to a topic they have either posted, or commented on.

Additionally, we will need to allow each person to opt-out of email notifications in various different ways: 
- opt out for a specific thread
- opt out for all comments
- opt out entirely

Tech Specs:  This task would best be accomplished by porting an existing Drupal module for the job. Here is a [comparison list of related modules](https://groups.drupal.org/node/15928).  The two that are currently under consideration are [Subscriptions](http://drupal.org/project/subscriptions) and Notifications](https://www.drupal.org/project/notifications).

**Comment by jenlampton** [comment]
Comment from @Dinornis on https://github.com/backdrop-ops/forum.backdropcms.org/issues/5#issuecomment-275830117

> Allow users to subscribe / unsubscribe from email updates

In my opinion this should be on the MVP list.

**Comment by jenlampton** [comment]
Comment from @jenlampton on https://github.com/backdrop-ops/forum.backdropcms.org/issues/5

>  In my opinion  Allow users to subscribe / unsubscribe from email updates should be on the MVP list.

This one goes hand-in-hand with `Email people when activity happens on the thread`.  There's no point in subscribing to something if the site can't send an email. And we can't start emailing people without a way for them to opt-out of those emails.

We know this is an important feature. The only reason we didn't have it on the MVP list is because it's very hard to do. We thought it would be better to start with follow (which is similar), launch the site, then return to focus on the harder stuff.

**Comment by jenlampton** [comment]
Comment from @Dinornis on https://github.com/backdrop-ops/forum.backdropcms.org/issues/5

In my experience, forums that do not provide this feature struggle with abandoned threads and lack of activity in general.
> This one goes hand-in-hand with Email people when activity happens on the thread. There's no point in subscribing to something if the site can't send an email. And we can't start emailing people without a way for them to opt-out of those emails.

Emails go out only to people who are subscribed and they can choose which threads they subscribe to.  The [Notifications module](https://www.drupal.org/project/notifications) should cover this.

Here is a [comparison list of related modules](https://groups.drupal.org/node/15928).

**Comment by jenlampton** [comment]
I've also had a lot of success with the [Subscriptions](http://drupal.org/project/subscriptions) module.

**Comment by docwilmot** [comment]
> The two that are currently under consideration

From the [comparison matrix](https://groups.drupal.org/node/15928) looks like Message Stack is winning though.

**Comment by jenlampton** [comment]
@docwilmot why do you say that? What from that list is relevant to our forum, that puts that one ahead?

**Comment by docwilmot** [comment]
> Usage statistics 2014-11-09:
25,408 increasing (Message)
23,387 increasing (Message Notify)
5,999 increasing (Message Subscribe)
6500, stable (Subscriptions)
9100, declining (Notifications)

**Comment by Dinornis** [comment]
[Subscriptions](https://www.drupal.org/project/subscriptions) may provide the functionality needed yet be easier to implement out of the box.
* Ability to subscribe to nodes or taxonomies.
Being able to subscribe to taxonomies allows users to subscribe to specific forums.  This is something I was not able to setup with Notifications.
* Makes it easy for users to change their subscriptions while viewing a node.
* Allows users to auto-subscribe to posts/comment they made.
* Adds a tab to users screen for managing their subscriptions.

**Comment by docwilmot** [comment]
@jenlampton what we thinking here? Still Subscriptions, or we going with the new Message kids?

**Comment by jenlampton** [comment]
Sure :)

**Comment by docwilmot** [comment]
Oh this wasn't a recommendation!  I have no idea what's best here.

**Comment by docwilmot** [comment]
I ported Node Notify module and integrated it with the "Follow" Flags. This is a lightweight solution which allows users to subscribe to get emails from individual Forum node comments, but not entire Forums (taxonomy). Is this enough for now, or should we port a more advanced solution (Message stack, or Subscriptions or Notifications).

To expand the options in the original post, we **could** have options:
- [x] Subscribe to get email for every comment on every topic (*not done but easily doable with custom code*)
- [x] Choose to pause receiving any emails at all via a switch in account settings (*not done yet but easily doable with custom code*)
- [x] Topic creator get email for every comment with option to opt out
- [x] Users choose to follow a certain topic 
- [x] Users get email for every topic which they commented in (with opt out option) (*not done yet but easily doable with custom code*)
- [ ] Emails on all comments certain Forums (user chooses)

The last one would need either custom code to integrate a new Flag or the more advanced modules mentioned above. 

- [ ] Emails from `@mentions` (*this has a separate issue*)

@jenlampton any thoughts?

**Comment by docwilmot** [comment]
Question:
For the purpose of having a switch in user settings to pause **emails** (while keeping all "Follow" Flags), we could port a more advanced module, we could add a custom table to store user preferences, or we could use a Flag. Which one is most appropriate? I'm not sure about if Flag can be used this way, ie we can `form_alter` the user settings form (or create a new menu callback) and have a form which saves a Flag setting for that user.

This would not give us granular control over which topics/categories to get emails from. There would be controls to Follow individual topics, controls to follow categories, but only one switch to get emails or no emails. Do we need granular control?

**Comment by jenlampton** [comment]
No. In fact, I don't think we need this feature all. If we add too much to
this site it's going to be a nightmare to maintain. Less is more, at least
for the foreseeable future.

**Comment by docwilmot** [comment]
PR pushed:
- adds `node_notify` module
- adds `borg_flag_notify` module (custom) which:
  - integrates the Follow flags with notifications to allow Follows to be converted to Notify subscriptions and vice versa
  - hides the default 'subscribe' links from node notify, since we're using Flags
  - still allows users to opt out of email notifications per followed node (this is default Node notify behaviour)

To do/consider:
- use Mail Queue module when users increase

**Comment by BWPanda** [comment]
Apologies for not having read through all of this before posting, but is this still needed? I believe users can follow threads now and be notified of new comments, etc.

**Comment by jenlampton** [comment]
@BWPanda thanks for the follow-ups on these old issues :) I've created https://github.com/backdrop-ops/forum.backdropcms.org/issues/103 to keep track of the need to handle email as recommended by @docwilmot, so I guess this issue can be closed?
