### ISSUE TITLE
Remove 'Footer Menu' text from footer

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/forum.backdropcms.org#100]
The text "Footer Menu" appears in the footer. This is the block title of the footer menu and should be hidden/removed.

![Footer menu screenshot](http://i.imgur.com/oUEBXXY.png)

**Comment by jenlampton** [comment]
I saw this on my local site, but not on live. What page did you see this on?

**Comment by BWPanda** [comment]
@jenlampton Homepage of the Forum: https://forum.backdropcms.org/

**Comment by jenlampton** [comment]
Fixed! :)
