### ISSUE TITLE
Set up Tugboat for testing PRs

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/forum.backdropcms.org#105]
In today's meetings we discussed setting up a tugboat workflow where each PR against backdropcms.org could be tested in a sandbox before merge.

To do this, someone will need to look at the way we have the demo site set up, and add a similar `tugboat.yml` file into this repo. Then, they will need to log into https://tugboat.qa/ (using credentials from the Backdrop 1Password account -- sysadmin level) and associate a tugboat instance with this repository.

Related: 
https://github.com/backdrop-ops/backdropcms.org/issues/621
https://github.com/backdrop-ops/api.backdropcms.org/issues/80

**Comment by BWPanda** [comment]
Here's a PR: https://github.com/backdrop-ops/forum.backdropcms.org/pull/113

I tested it in my repo, and it works nicely; https://github.com/BWPanda/forum.backdropcms.org/pull/1
(note that that comment says the username to login is 'admin', but I made a subsequent commit to the code to change it to 'drop' instead (for the forum site)).

**Comment by BWPanda** [comment]
I figure we can test and merge this PR, then once we know it's working 'in the wild', we can commit similar PRs to the other B.org repos.
