### ISSUE TITLE
Show a "date posted" column

### ISSUE THREAD

**Issue by laryn** [backdrop-ops/forum.backdropcms.org#106]
[Via the forum itself](https://forum.backdropcms.org/forum/display-and-allow-sort-post-date-forum-listings):

> minor request: at the moment, forum posts are only sortable by the last comment, it would be useful to also see/be able to sort on the date the post was submitted.

![Screen Shot 2020-01-29 at 10 11 15 AM](https://user-images.githubusercontent.com/871421/73374385-b4cf8480-427f-11ea-8366-ad8a96be1a05.jpg)

**Comment by BWPanda** [comment]
Here's a PR: https://github.com/backdrop-ops/forum.backdropcms.org/pull/114
