### ISSUE TITLE
Easily find the most meaningful comments/answers

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/forum.backdropcms.org#13]
As a forum visitor, I need to be able to **easily** find the most meaningful answers. 

We are collecting several data points about comments that could tell us if they are meaningful
* The author of the post can mark a comment as `The accepted answer`
* Other forum visitors can mark a comment as `Helpful`

Technical specs: In addition to showing the complete list of threaded comments, we should add two other views ABOVE the complete list of comments:
* The accepted answer should come first (Styled differently than the others)
* Comments that were marked as `Helpful` should come second, after the accepted answer, sorted by how many people found them Helpful. (This list should be limited to something like 5 of the most Helpful comments)

**Comment by docwilmot** [comment]
@jenlampton we could:
- modify the `node.tpl.php` or `comment.tpl.php` to insert the accepted and helpful comments
- build a custom `node/%` Layout for forum content type, and split node body and comments into blocks, then put the accepted and helpful comments as blocks also.

Any preference?

**Comment by jenlampton** [comment]
> build a custom node/% Layout for forum content type, and split node body and comments into blocks, then put the accepted and helpful comments as blocks also.

This is my preference. It will be easier to maintain long-term the less custom code we need. :)

**Comment by docwilmot** [comment]
We will need to port [flag limits](https://www.drupal.org/project/flag_limit) for the "accepted answer" flag to be meaningful. Otherwise people will be able to select multiple "The accepted answer"s

**Comment by docwilmot** [comment]
We will also need Comment Block module (already ported)

**Comment by jenlampton** [comment]
Or, we could use a view. Which would be a lot less overhead for maintenance.

**Comment by docwilmot** [comment]
With reference to the "accepted answer" comment, I am referring to the fact that there is no way to stop a user clicking this flag on *multiple* comments, which doesnt make sense (there should only ever be one). I've already built the View for display.

Re comment block now, yes we could use a View and I considered that but there is currently no way I know to get *threaded* comments in a View, and no way to get just the full theme comments in a view without the node following it, and no way to get the comment form. We would need to write a bunch of custom code, which, fortunately, the Comments Block guys have already done. 😄 Its actually quite a simple module.

**Comment by jenlampton** [comment]
> With reference to the "accepted answer" comment, I am referring to the fact that there is no way to stop a user clicking this flag on multiple comments, which doesnt make sense (there should only ever be one). I've already built the View for display.

Right, but there's no need to add a module for that. As long as we only ever display one, that's all that matters.

**Comment by jenlampton** [comment]
> Re comment block

Or, you could just display "the node" with all fields hidden in the view mode to get the comment thread. Then use a view to display "the node" in a separate block above.

**Comment by docwilmot** [comment]
> As long as we only ever display one, that's all that matters.

Compromise: looking at the Flag Limits module, we only need a tiny fraction of the code there, shown here adapted for our use:
```
/**
 * Implementation of hook_flag().
 */
function borg_flag_notify_flag($action, $flag, $content_id, $account) {
  // If a user flags an "accepted" comment, unflag any others he had accepted before.
  if ($action == 'flag' && $flag->name == 'accepted') {
    $query = "SELECT * FROM {flag_content} WHERE fid = :fid AND uid IN(:uid, 0) ORDER BY timestamp DESC";
    $result = db_query($query, array(':fid' => $flag->fid, ':uid' => $account->uid));
    while ($row = $result->fetchObject()) {
      flag('unflag', $flag->name, $row->content_id, $account);
    }
  }
}
```



> Or, you could just display "the node" (with all fields hidden in the view mode) to get the comment thread. Then use a view to display "the rest of the node" in a separate block above.

That is sounding awfully hacky and I really dont like it. 

Again though, the useful parts of the contrib module are thankfully quite easy: the comments are stored in a static variable then unset from the node in a `_node_view_alter()`, then same comments put in a block. That would be trivial to copy into `borg_forum` module.

**Comment by alexfinnarn** [comment]
I like StackOverflow's up/down voting feature. Implementing that via a flag count (at least I think it does more than booleans) would help with removing "bad" answers and giving users answers that are most accepted at the time the user views it. 

For example, if I ask a question when Backdrop 1.8.x is out, accept an answer, and then someone else goes to that topic on Backdrop 1.9.x, there is no guarantee that my accepted answer is the best at that time. The answer might not even work anymore. 

At that point, you only have "helpful" answers that I as a user could promote. If you start getting 50+ answers on a forum topic and 30 of those comments are helpful, how do I sort through those to get the "most helpful" comment to read? 

Up/down voting or "7 out of 8 people found this helpful" would help users in that regard, I think. Plus, with enough downvotes, even a comment that isn't spam or abusive could gain enough negative votes to be removed or greyed out.

**Comment by jenlampton** [comment]
we've already addressed this in:

> Comments that were marked as Helpful should come second, after the accepted answer, sorted by how many people found them Helpful. (This list should be limited to something like 5 of the most Helpful comments)

**Comment by docwilmot** [comment]
@alexfinnarn thanks for the testing and comments. The Most Helpful list is, as @jenlampton says, a limited number (currently limited to 3), ranked by number of flags. So realistically I think it accomplishes the aim of the up/down voting feature: users get the "most helpful" answers visibly. 

And I agree there are a bunch more things we can add, and we do have plans, but starting slowly. Right now we're still using core comments, and to get them to float based on a Flag would take some coding. We considered Views, and that might still be a future possibility, but it would take a lot of themeing to do right. 

Also considered the styling based on votes (and adding a vote count to the comment), maybe later. If you have the time to put your ideas to code, would be appreciated. 

Good ideas though.

**Comment by BWPanda** [comment]
I believe this can be closed now (this functionality exists on the forum). I've opened a follow-up issue [here](https://github.com/backdrop-ops/forum.backdropcms.org/issues/81) where I propose better ordering of comments.
