### ISSUE TITLE
Add a block to user page that shows users priority picks

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/forum.backdropcms.org#132]
On the original survey site, we had a block that showed which issues a user had voted for. They could then visit any of those issues and change their vote. 

![image](https://user-images.githubusercontent.com/3144571/156693741-17a349ff-2524-4627-9920-9f5931df22d6.png)

**Comment by stpaultim** [comment]
I went ahead and created block on the user profile page that lists each users votes. I did this directly on production site, so the config needs to be committed. 

Atten @jenlampton or @bugfolder

**Comment by jenlampton** [comment]
committed.

**Comment by jenlampton** [comment]
Oh but @stpaultim can we please not call people "users"

**Comment by jenlampton** [comment]
Ah, just checked the site and saw it has been changed to `My Favorite Feature Requests` :D 
thank you!
