### ISSUE TITLE
Add Total Votes to feature listings - and sort by votes

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/forum.backdropcms.org#137]
We need some way to float important or popular issues to the top, not everyone will want to review them all. Also, I think a default listing of features in order of popularity is helpful and will help stimulate discussion. 

If someone voted for two issues that are both tied overall, they can boost their favorite by removing their vote for the other. We want to help folks visual their choices as well as the impact. 

![image](https://user-images.githubusercontent.com/3144571/156697243-65618820-a831-4542-965e-f3ad43be10f4.png)

**Comment by stpaultim** [comment]
@jenlampton - I have a PR that modifies the view to add a vote column AND adds the exposed filters shown here. Then, we'd just have to add a menu link to this page to get started.

**Comment by jenlampton** [comment]
This change is now live: https://forum.backdropcms.org/feature-requests
