### ISSUE TITLE
Users searching in the forum should optionally be able to limit results to forum posts or feature requests

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-ops/forum.backdropcms.org#144]
Since the creation of large quantities of forum nodes that are feature requests (#142)  (I do think forum is the right place for this), search results for forum discussions can be swamped by feature request nodes.

Please include an optional filter to either forum posts, feature requests or any.

**Comment by yorkshire-pudding** [comment]
@bugfolder @docwilmot @stpaultim @herbdool @BWPanda @jenlampton @quicksketch 
Sorry for pinging lots of you but you are listed as website admins for the forum and I think you're around more than others.

The forum search is pretty much unusable as it stands as the results are swamped by feature requests.  This request is now 3 months old.  I'm fairly sure it would be straightforward to either expose advanced search to logged in (or anonymous) so can filter, or exclude feature requests from search - it has its own filter.

**Comment by jenlampton** [comment]
Oh yeah, that should be a quick config change!

**Comment by jenlampton** [comment]
I've excluded polls and feature requests from the search index.

**Comment by yorkshire-pudding** [comment]
Thanks @jenlampton - much appreciated
