### ISSUE TITLE
Need for a Forum description

### ISSUE THREAD

**Issue by Graham-72** [backdrop-ops/forum.backdropcms.org#17]
I would like to be able to read an introductory paragraph at the head of a forum giving a summary of its purpose, intended audience, administrator etc.

I confess to being a bit puzzled by seeing two forums here - is one a trial of the qa_forum module?

**Comment by jenlampton** [comment]
> I would like to be able to read an introductory paragraph at the head of a forum

I think that's a great idea, but when we launch there will be only one "forum" so it will be less confusing.

> I confess to being a bit puzzled by seeing two forums here

Yes, there are currently three, but only for compare / contrast purposes.

**Comment by docwilmot** [comment]
This is done.
