### ISSUE TITLE
Paragraphs module evaluation (simplytest.me export kit)

### ISSUE THREAD

**Issue by LeeteqXV** [backdrop-ops/forum.backdropcms.org#22]
Below are files you can easily import into a new test site at https://simplytest.me to get a setup of the flag+paragraphs+views/slideshow modules, to see how they fit together. This is relevant for the forum discussion about the perspectives of using comment_mover , as the paragraphs module makes it possible to add taxonomy etc. to each discussion point in a post, then move it out on its own node when appliccable. This is relevant for the CMX.arbolis.net distributions which we hope to base on BackdropCMS.

**Instructions:**
1. See the screenshot below with the modules list; open a new test site at simplytest.me with those modules pre-installed (no configuration needed, just import the database).
2. Activate the Backup_Migrate module and got to its configuration->Restore page.
3. Restore the files backup (attachment below) first (before the DB!!). Need to change the "Restore to" dropdown box to "Public Files directory")
4. Restore the database (attachment below)
5. Clear all caches.
6. Go to the front page and check out the examples. 

Have fun :-)

**3 attachments:** modules list screenshot, publicfilesfolder, db-backup

![paratesting_simplytestme_modules_list_screenshot](https://cloud.githubusercontent.com/assets/19711572/24524013/649a3150-1595-11e7-9582-fe8f18afcedf.png)
[Paratesting1y_filesfolder-2017-03-10T15-05-32.tar.zip](https://github.com/backdrop-ops/forum.backdropcms.org/files/883693/Paratesting1y_filesfolder-2017-03-10T15-05-32.tar.zip)
[Paratesting1y-2017-03-10T15-04-57.mysql.zip](https://github.com/backdrop-ops/forum.backdropcms.org/files/883694/Paratesting1y-2017-03-10T15-04-57.mysql.zip)

**Comment by LeeteqXV** [comment]
Crossreferencing the effort of porting the Paragraphs module:
https://github.com/backdrop-ops/contrib/issues/212

**Comment by docwilmot** [comment]
Wont be considering Paragraph module for Forum any time soon; going with simple Views/Comments/Flag mashup. Reopen if becomes relevant again.
