### ISSUE TITLE
How to build a category listing with Views

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/forum.backdropcms.org#25]
@jenlampton I have had a look at the Forum this evening and I think we may need to make some sacrifices if we insist on building our Forums with pure Views/Taxonomy. I believe we can agree that we need a View that lists all the Forum categories (Taxonomy terms). We have two such listing Views (See https://forum.backdropcms.org/): a content view (header says "Category") and a taxonomy term View (header says "All Categories"). 
The content View lists a new row with every node (forum topic) that is created, so it cant work. I have tried aggregating and using DISTINCT queries, but then this makes comment counts impossible.
The taxonomy View does the listing right, and we get a list of topics as we need, but then the last comment timestamp becomes impossible.
So this needs some decision.

**Comment by jenlampton** [comment]
Would you be able to get last comment timestamp using something like [views_field_view](https://www.drupal.org/project/views_field_view)?

**Comment by docwilmot** [comment]
Did custom handlers.
