### ISSUE TITLE
Can we have a code formatting/hightlighting library?

### ISSUE THREAD

**Issue by serundeputy** [backdrop-ops/forum.backdropcms.org#30]
On my site I use `highlight.js` by putting the following in `page.tpl.php`

```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.1/styles/default.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.1/highlight.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
```

this way we can callout inline code references and block code references that could be useful in many posts and howtos.

* https://forum.backdropcms.org/forum-topic/where-should-i-put-my-config-directories
* https://forum.backdropcms.org/forum-topic/get-started-dev-environment-quickly

----
PR: https://github.com/backdrop-ops/forum.backdropcms.org/pull/34

**Comment by serundeputy** [comment]
Some examples:
![screen shot 2017-11-03 at 7 42 23 pm](https://user-images.githubusercontent.com/6763671/32399751-2b4c1090-c0cf-11e7-9b4e-3b72f9e401f2.png)

Styles:
<img width="931" alt="screen shot 2017-11-03 at 7 43 58 pm" src="https://user-images.githubusercontent.com/6763671/32399771-6046cb0a-c0cf-11e7-8b03-a6a61e60689d.png">

**Comment by docwilmot** [comment]
I'll leave this one for @jenlampton to decide.

**Comment by jenlampton** [comment]
I wonder if there's a markdown filter we could use instead? (or in addition?)

**Comment by jenlampton** [comment]
@serundeputy I've merged your PR for now, but I would prefer to see something that's more standard to use long-term.

**Comment by alexfinnarn** [comment]
I love HighliughtJS! Woot!

Looks like HighlightJS has markdown support https://highlightjs.org/download/ but nesting blocks with a PHP block inside of a Markdown style doesn't work when I tried it on https://forum.backdropcms.org/forum-topic/test-post-about-styles. I'm probably doing it wrong...

**Comment by serundeputy** [comment]
@alexfinnarn check out https://forum.backdropcms.org/forum-topic/test-post-about-styles#comment-33

which attempts to explain the convolution.

**Comment by alexfinnarn** [comment]
Thanks. I forgot about the extra `<code>` tags. Seems to work fine for me with those linked instructions.

**Comment by jenlampton** [comment]
Closing, since we have highlight.js.
