### ISSUE TITLE
Provide sanitized DB and file backups for devs to help dev on forum.backdropcms.org

### ISSUE THREAD

**Issue by serundeputy** [backdrop-ops/forum.backdropcms.org#31]
In: https://github.com/backdrop-ops/backdropcms.org/issues/358 we implemented automated sanitized backups of backdropcms.org for devs to get the things they need to help with PRs.

Perhaps @larsdesigns (or someone with server access @quicksketch) can implement an instance of https://github.com/serundeputy/sql-dump-sanitize for forum.backdropcms.org so other devs can pitch in as well?

**Comment by docwilmot** [comment]
Good one @serundeputy

**Comment by larsdesigns** [comment]
@serundeputy: Yes, I think that can be arranged.

**Comment by larsdesigns** [comment]
1. Implemented for forum.backdropcms.org. See https://github.com/backdrop-ops/backdropcms.org/issues/470 for details.

**Comment by serundeputy** [comment]
thanks @larsdesigns !
closing.
