### ISSUE TITLE
[DX] Update README.md with instructions to get local dev running.

### ISSUE THREAD

**Issue by serundeputy** [backdrop-ops/forum.backdropcms.org#38]
Add steps to set up local dev. Pending #36 

----

PR: https://github.com/backdrop-ops/forum.backdropcms.org/pull/92

**Comment by jenlampton** [comment]
#36 has been closed. Do we still need this issue? If so, can you elaborate what's needed?

**Comment by serundeputy** [comment]
Update README.md on how to get working with `lando`.

**Comment by olafgrabienski** [comment]
@serundeputy I'm considering to help with some minor theming / styling issues for the forum, so a `lando` instruction for local dev would be helpful.

**Comment by serundeputy** [comment]
@olafgrabienski @larsdesigns https://github.com/backdrop-ops/forum.backdropcms.org/pull/92

safe to merge right away as these are just DX/community help improvements and do not effect site functionality.

**Comment by olafgrabienski** [comment]
@serundeputy Thanks for adding the *Lando* instructions. I don't know when I'll get round to help with forum issues, but I'm sure the instructions will be helpful.

**Comment by serundeputy** [comment]
Merged https://github.com/backdrop-ops/forum.backdropcms.org/pull/92 per outreach meeting on 14 November 2019

@stpaultim and @olafgrabienski and anybody interested if you'd give those README.md instructions a spin and see if they need any updating, clarification, or other improvements that would be great!

closing this.
