### ISSUE TITLE
Formatting Options - UI glitch

### ISSUE THREAD

**Issue by aybase** [backdrop-ops/forum.backdropcms.org#40]
There's a minor issue with the "Formatting Options" show/hide span in the Add Comments to post area. 

<img width="579" alt="screen shot 2017-11-10 at 11 49 29 am" src="https://user-images.githubusercontent.com/16908523/32669784-c2137578-c60f-11e7-8b98-141e5c648078.png">

**Comment by aybase** [comment]
It's likely that this inline style is conflicting   

`<h3 style="display: none;">Filtered HTML</h3>`

**Comment by olafgrabienski** [comment]
If `display: none` for the heading is needed, a top margin for the list of tips could fix the issue:

```
.tips {
  margin-top: 3em;
}
```
(Not sure if `.tips` is used elsewhere on the site.)

**Comment by BWPanda** [comment]
This seems to have since been fixed, as I cannot see this issue anymore. Please re-open if you're still experiencing this.
