### ISSUE TITLE
Improve main menu styling

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-ops/forum.backdropcms.org#45]
The styling of the forum's main menu looks a bit provisional in comparison to backdropcms.org:

- Active menu items are not highlighted so far.
- On hover, the font color is too dark, and the bottom border is not well aligned (see screenshot below).

![screen-backdrop-mainmenu-forum](https://user-images.githubusercontent.com/14188307/33154192-fbf73794-cfe6-11e7-9ca5-f4120d584554.png)

**Comment by jenlampton** [comment]
I've applied the styles from the drop-down menu on the main site. Let's see if these are adequate, or if we need further refinement.

**Comment by olafgrabienski** [comment]
@jenlampton, thanks for applying the styles! With that change, also hover seems to not be highlighted anymore. Which is much better than before.

Should we however introduce highlighting? In my opinion, it helps with orientation on the site.

**Comment by jenlampton** [comment]
> Should we however introduce highlighting? In my opinion, it helps with orientation on the site.

Yes, I think we need something. Maybe a white underline to indicate the current section?

**Comment by BWPanda** [comment]
This seems to have been done now - hover highlighting and the same highlighting for active links. Closing.
