### ISSUE TITLE
Access denied message after creating an account.

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/forum.backdropcms.org#48]
See https://forum.backdropcms.org/forum-topic/error-messages-new-users-main-site-and-forums

**Comment by BWPanda** [comment]
I just registered a new account and this is what I see:

![image](https://user-images.githubusercontent.com/2385329/103852520-1e971600-5100-11eb-9bad-b52df16d5c51.png)

When I click the link in the email and enter a new password for myself, I see this:

![image](https://user-images.githubusercontent.com/2385329/103852624-5b630d00-5100-11eb-852d-39bc15ac1100.png)

So I think we're all good now (guessing the issue previously was related to the shared sign-in system we ditched).
