### ISSUE TITLE
Ability to edit your own posts (and maybe show diff/revisions)?

### ISSUE THREAD

**Issue by laryn** [backdrop-ops/forum.backdropcms.org#49]
Should we allow people to edit the initial post? If so, perhaps revisions should be turned on by default, and we can maybe show revisions in a "diff" style display. (See the [Diff](https://www.drupal.org/project/diff) module for example).

**Comment by jenlampton** [comment]
I'm not sure I see the value of having revisions on topics, but I do think we should allow everyone to edit their own posts. (I've granted that permission). Can you convince me why revisions should be turned on? :)
