### ISSUE TITLE
Show which posts have an accepted answer in forum list view

### ISSUE THREAD

**Issue by laryn** [backdrop-ops/forum.backdropcms.org#50]
For example, a [list like this](https://forum.backdropcms.org/forums-custom/how-and-troubleshooting) could have posts that have an accepted answer in green and/or with a checkmark or something.

**Comment by docwilmot** [comment]
This is a good idea. I've added a class to the rows in the topics lists to show if they have accepted answers. Some rows have more than one accepted answer (probably when the user changes his answer the flag entity stays, dont know) so the class shows as `accepted-0` or `accepted-1` or `accepted-2` etc. Did this through the Views UI. 

We could use CSS now:
```
tr:not(.accepted0) :not(th) {
  background-color: blueviolet;
}
```

Will leave to @jenlampton to style if she agrees.

**Comment by jenlampton** [comment]
I also think this is a good idea, but I don't think a change in the color will be enough of a cue that the post has an accepted answer. Can we add another column called "Status", maybe with the text "Answered" for those that have answers?

**Comment by LeeteqXV** [comment]
BOTH with the word "Answered" (or graphical symbol indication) and by
coloring the text, IMO.

**Comment by docwilmot** [comment]
Yes, you're right, I was a bit hasty with this. Not sure I like a new column just for this though, could we have a check mark or a thumbs up icon or even the word "answered" next to the title?

**Comment by jenlampton** [comment]
> Not sure I like a new column just for this though, could we have a check mark or a thumbs up icon or even the word "answered" next to the title?

I think we need to have some text on the page (or people won't know what the checkmark will mean either) but putting it next to the title is fine by me 👍

**Comment by docwilmot** [comment]
I dont know how to add an ARIA attribute, but the rest can be done in CSS?

**Comment by jenlampton** [comment]
I'll take a stab at it :)

**Comment by jenlampton** [comment]
In our design meeting today @klonos suggested adding something that looks like a tag from github:
<img width="1016" alt="screen shot 2018-05-10 at 12 37 39 pm" src="https://user-images.githubusercontent.com/397895/39895979-3f4b49c8-5461-11e8-8dcb-f63212a3e1d6.png">

**Comment by jenlampton** [comment]
I've added something similar to the forum pages: https://forum.backdropcms.org/forum/how-and-troubleshooting

**Comment by jenlampton** [comment]
I'm going to close this issue in celebration, but if you would prefer color coding or something else, please reopen!
