### ISSUE TITLE
Notifications could use some improvement

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/forum.backdropcms.org#53]
**1. The emails for new comments use the following template:**
```
Hi [subscriber:name],

[comment:author] has commented on: "[comment:node:title]"

----

[comment:body]

----

You can view the comment at the following url
[comment:url]

You can stop receiving emails when someone replies to this post,
by going to [subscription:unsubscribe-url]

-- [site:name] team
[site:url]
```

I find it a bit unnecessarily wordy and propose simpler:
```
[comment:author] has commented on: "[comment:node:title]"

----

[comment:body]

----

You can view the comment at the following url
[comment:url]

You can stop receiving emails when someone replies to this post,
by going to [subscription:unsubscribe-url]
```

**2. The new topic notifications use the following template:**
```
[node:body]
----

You can view the discussion at the following url
[node:url]

You are receiving this email because you are following this forum category.

```

I propose the following to match the new topic notifications and add more detail:
```
[node:author] has posted a new topic: "[node:title]"
----
[node:body]
----

You can view the discussion at the following url
[node:url]

You are receiving this email because you are following this forum category.
```
**3. We should look into copying the GitHub technique of having the email sender be the name of the author of the forum post or comment instead of Backdrop's default "noreply"**

Not sure how this is done but I think it would be nicer.

**Comment by docwilmot** [comment]
We should also tweak the email subjects so that new topics and all their comments have the same title, so that Gmail can thread them properly.

**Comment by jenlampton** [comment]
I *love* all these ideas :)
