### ISSUE TITLE
Images uploaded to CKEditor are disappearing

### ISSUE THREAD

**Issue by laryn** [backdrop-ops/forum.backdropcms.org#56]
I recently ran into an issue with the Splashify module where images uploaded into CKEditor were not marked as permanent and were deleted. I modified some code that I found in the core block module for use with Splashify, to mark those files as permanent and it seems to be working. However, I think perhaps the forum has the same issue where uploaded images are not being saved permanently on replies on a topic. 

If that is the case, this would become a core issue -- comments are not saving images.

Reference: https://github.com/backdrop-contrib/splashify/issues/7

**Comment by jenlampton** [comment]
> If that is the case, this would become a core issue -- comments are not saving images.

yes, that's correct. We should implement the same fix in `comment_save()` as we did previously in `node_save()` in https://github.com/backdrop/backdrop-issues/issues/1373

**Comment by laryn** [comment]
As this is fixed in 1.9.2 I'll close this issue here and assume things to be working as soon as the forum is updated to the latest core!

**Comment by jenlampton** [comment]
Forum has been updated to the latest Backdrop version :)
