### ISSUE TITLE
Forum Categories

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/forum.backdropcms.org#6]
It will be important that the forums are helpful to people, and don't just become a place to get lost or a source of noise. If we start a discussion forum as part of backdropcms.org, how to we want to have it organized? 

Here's an initial list:

- Installation – Problems with getting it running
- How-To and Troubleshooting – Once it's running
- Custom and Contributed modules, themes & layouts – How to extend Backdrop CMS via the API
- Requests and Feedback – Feature requests; criticism.
- Miscellaneous – Almost everything else about Backdrop CMS

Let's keep our eyes open for other examples of forums that work, and continue to adapt and grow ours if necessary. Here are some sources:
* [WPs forums](https://wordpress.org/support/)
* [Drupal forums](https://www.drupal.org/forum)

**Comment by tomgrandy** [comment]
Thanks for getting this setup.  Here are my suggestions for top-level discussion areas

Installation
How-To
Modules
Themes
Layouts
Troubleshooting
Feature Requests

I think keeping the categories large enough to identify that they are putting their questions, feedback, comments in the right area or can **search** either within the forum or from Google to easily find a thread by keyword.

**Comment by jenlampton** [comment]
I'd prefer to start with the smaller list in the first post. Having too many things in too many places with nothing going on is going to be frustrating for people who are not getting the attention they need on their posts, as well as difficult to on moderators.

 We can split things out as we grow!

**Comment by BWPanda** [comment]
A few years on with the forums working and being used daily, how does this issue apply now? Still needed to discuss categories, or are we all good with the current ones:


- How-To and Troubleshooting
  *Help with getting things done and fixing problems.*
- Requests and Feedback
  *Tell us what you think about Backdrop and how we can improve.*
- Installation Questions
  *Questions about installing Backdrop, and issues after installation.*
- Meet-Ups and Events
  *Want to chat with others in your geographic area about Backdrop CMS? Connect here.*
- Backdrop Translations
  *Help translate the Backdrop User Interface. Use this forum for collaboration.*
- Usability Studies
  *Help us make improvements to Backdrop community websites and resources. Try one of the following scenarios and report back to us.*
- Other
  *Issues which do not fit into any of the other categories.*

**Comment by BWPanda** [comment]
I'm going to assume this is fine to close now.
