### ISSUE TITLE
Code snippets are going off the page

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/forum.backdropcms.org#60]
I saw two topics today with code snippets that spread off the page like this. 

![isue_with_update_1-9-5___backdrop_forum](https://user-images.githubusercontent.com/3144571/39787051-fdee3662-52e8-11e8-8341-f65408b73906.png)

**Comment by docwilmot** [comment]
`<pre>` tags dont wrap normally. We would need to add a `overflow: auto` to them like GitHub and others do.

```
The overflow property specifies what should happen if content overflows an element's box. auto | If overflow is clipped, a scroll-bar should be added to see the rest of the content. 
```

**Comment by jenlampton** [comment]
I've got a fix for this, coming today!

**Comment by jenlampton** [comment]
Fixed: https://forum.backdropcms.org/forum-topic/issue-update-1-9-5

**Comment by stpaultim** [comment]
I am reopening this issue. See:

https://forum.backdropcms.org/forum/sqlstatehy000-general-error-1364-field-itemid

![SQLSTATE_HY000___General_error__1364_Field__item_id____Backdrop_Forum](https://user-images.githubusercontent.com/3144571/68552721-c2434400-03df-11ea-9ddb-7550939119a1.png)

**Comment by serundeputy** [comment]
@stpaultim In this case https://github.com/backdrop-ops/forum.backdropcms.org/issues/60#issuecomment-552246708 it is a content issue.

The sql error is not in a `<code>` block just a `<p>`.

Not sure if we should close this ... but there  is no code issue to act on.

**Comment by jenlampton** [comment]
I added a codeblock around the error on that page. Closing.

**Comment by stpaultim** [comment]
Shouldn't there be something to prevent this from happening to a block of text using <p>. But, I agree that is another issue and should be it's own ticket.
