### ISSUE TITLE
Confusion with New Forum Topic button

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/forum.backdropcms.org#63]
I was just creating a new topic on the forum.backdropcms.org site. After completing my new topic, I clicked on the "New Forum Topic" button and wondered why it took me to a blank forum topic and why my recently created forum topic was not listed anywhere. 

After trying again, I realized my error when I saw the smaller "Save" button to the right. 

SUGGESTION: Maybe remove the "New Forum Topic" button from this page. You would NEVER need this button, if you are already at: /node/add/forum-topic/

Whereas, you may be silly like me and think that this is the button to save your recently created forum topic. I realize that this was a pretty stupid mistake, but I'm guessing there are people who will make it and may loose a significant amount of work when they do.

![create_forum_topic___backdrop_forum](https://user-images.githubusercontent.com/3144571/41750853-e014ef7e-7583-11e8-8096-8c52e4064895.png)

**Comment by jenlampton** [comment]
Great idea @stpaultim, thanks! The button has been removed on all node/add/* pages.

**Comment by stpaultim** [comment]
I'm still seeing it here: https://forum.backdropcms.org/node/add/forum-topic

**Comment by jenlampton** [comment]
Interesting, I don't think this visibility condition is working...

**Comment by jenlampton** [comment]
Oh, there we go. User error :)

**Comment by stpaultim** [comment]
Sorry, but I think this needs to be node/add/*/* if that is possible. 

If I try to create a new topic from within an existing forum, I still get the "new topic" button.

![create_forum_topic___backdrop_forum](https://user-images.githubusercontent.com/3144571/42354336-c56eb2b4-808b-11e8-9a86-5cae59d51132.png)

**Comment by jenlampton** [comment]
How bout now?

**Comment by stpaultim** [comment]
I think it's good. I can't seem to recreate the problem anymore. Thanks.
