### ISSUE TITLE
Comment form and all comments showing up twice

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/forum.backdropcms.org#64]
I'm seeing two comment forms on each topic in the BackdropCMS forums. One labeled "Comments" and one labeled "Add Comment." 

One would probably be enough. :-)

UPDATE: All comments are being displayed twice, including the new comment form. Once they are being displayed with the Accepted Answer Block and once without. Unfortunately, the second batch of listing includes the Accepted Answer Block, so you have to scroll through the entire list of comments once before you get to the Accepted Answer.

![login_form_is_missing___backdrop_forum](https://user-images.githubusercontent.com/3144571/43344912-2c15b7fc-91b1-11e8-91cc-dfbad8c1329e.png)

**Comment by stpaultim** [comment]
Here is another screen shot that might be helpful. This shows that both a user comment and the new comment form are both being repeated.

![screencapture-forum-backdropcms-org-forum-automatically-clear-cache-while-theming-2018-07-27-15_28_28](https://user-images.githubusercontent.com/3144571/43345099-dd46347a-91b1-11e8-9574-40697c2e634b.png)

**Comment by jenlampton** [comment]
I have committed a fix for this and it will go live later today.

**Comment by stpaultim** [comment]
As far as I can tell, the fix is working great!
