### ISSUE TITLE
Volunteer

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/forum.backdropcms.org#65]
I've be interested in helping with the forum if help is needed. Occasionally, I try to drop in and answer any basic questions. But I would be also willing to:

1. Help moderate SPAM 
2. Help with technical aspects of forum.backdropcom.org
3. Discuss feature and UI improvements.

I have a history and background working with tech support AND forum moderation, if that is helpful. Just let me know if any help is needed.

**Comment by jenlampton** [comment]
I have promoted you to a moderator on the forum. Please let me know if there's anything you need access to on the site that you do not have currently :)
