### ISSUE TITLE
Auto post new forum topics to Gitter

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/forum.backdropcms.org#69]
Lately, I've been watching for new topics in the forum and either replying myself and/or posting a link in Gitter to let other folks know about the topic. I think that one way to engage new folks in Backdrop is by being responsive in the forum. 

Recently, @laryn suggested that we might be able to automatically post new forum topics in Gitter. He (and I) are not sure if this is a good idea, but I thought it worth posting for discussion. 

In my opinion, this is probably not a good idea over the long term (if the forum gets busier), but it might make sense for the time being, while resources are limited and the active community remains fairly small. If the forum does get busier, the problem of responsiveness will hopefully solve itself.

**Comment by klonos** [comment]
I do not object this for now (while we are still a small community), but at a later point it might become an issue if forum topics are created every minute 😄 ...but we can alway disable this if it becomes an issue.

**Comment by serundeputy** [comment]
PR: https://github.com/backdrop-ops/forum.backdropcms.org/pull/93

Ready for Review.

* Added new module `borg_gitter`
* Checks for new `forum_topic` node
* on `node_insert` posts to gitter channel backdrop/backdrop-issues

```
A new post is on the forum: {{ gitter xi }: https://forum.backdropcms.org/forum/gitter-xi

Pitching in on the forum is a great way to feel good and contribute to the Backrop Community.

:smile: :heart: 
```

Deploy
--------

- [ ] pass QA; merge PR and pull code to f.b.org server
- [ ] Need a gitter API token in `settings.local.php` or whatever file is on the sever that is not in version control
  * during testing I was using my API token ; which posts as me
  * we should create a ForumBot account and get it an API token and put that in the settings file

```php
// Gitter api token
$settings['gitter_token'] = 'FORUMBOT_API_TOKEN';
```
- [ ] enable the `borg_gitter` module

**Comment by stpaultim** [comment]
Not sure if there is anything I can do on this yet. Maybe if I had a local version of forum working, but I don't yet. Might try to make that happen today.

**Comment by jenlampton** [comment]
Merged the PR.

> we should create a ForumBot account and get it an API token and put that in the settings file

We already have a DragonBot account we use for this purpose. I spent about a half hour trying to find or request a "Gitter API token" but didn't come across any info. @serundeputy  Can you please post a link to some docs?

**Comment by jenlampton** [comment]
It just occurred to me that the DragonBot account posts to gitter all the time via the [bot](https://github.com/backdrop-ops/dragonbot). I don't think I have access to the Roku, but @serundeputy I think you do.

**Comment by serundeputy** [comment]
Gittter API: https://developer.gitter.im/apps
whatever user you sign in as it will generate a token for that user; I can not sign in as `DragonBot` as I don't have those creds.

I can't find `DragonBot` on the localize server which is the one I have access to.

I found a `DragonBot` token on my local install of hubot (which is not the one on the server), and it works (tested locally).

I don't have write access to the `forum/settings.local.php` file so I could not wire it up in there.

@jenlampton I'll send you the token through some secret transfer service

**Comment by jenlampton** [comment]
Tested locally, works like a charm! Deploying now :)

**Comment by jenlampton** [comment]
Deployed :)
