### ISSUE TITLE
Failure to import forum.settings

### ISSUE THREAD

**Issue by Graham-72** [backdrop-ops/forum.backdropcms.org#7]
I have hit a problem trying to install a trial forum site from this project's repository.

I forked my own copy and installed it on my server. I successfully used it to install a new Backdrop site and enabled the contributed modules, including Forum. With the config settings from the repo in their required place I tried to synchronise but got this result:
![configuration management forum oliverhosting uk](https://cloud.githubusercontent.com/assets/10559274/22388764/21c06e08-e4da-11e6-81fe-1f98bce93009.png)

I then checked and confirmed that Forum is is enabled. I then looked at the required changes:
![configuration management forum oliverhosting uk 1](https://cloud.githubusercontent.com/assets/10559274/22388868/c72b47dc-e4da-11e6-8a2a-41ebc0917703.png)

Why are these not being accepted?

**Comment by jenlampton** [comment]
Ah, I expect the config files in the repo are not up to date. I have just committed everything from the site as they are now, can you give it another pull, and see if that fixes it?

**Comment by Graham-72** [comment]
> give it another pull, and see if that fixes it

Yes thanks, configuration now syncs.

But now the view 'Following' gives me 'This view is looking for a flag by the name "follow", but there is no such flag. Perhaps it was deleted. Please update the relationship "Flags: follow by current user" in this view to use an existing flag.'

Should this be found in flag.settings?

**Comment by jenlampton** [comment]
> Should this be found in flag.settings?

I would assume it is in a flags.flag.follow.json, but those files don't seem to exist, so perhaps that info is still in the DB. It looks like perhaps flag module has not been completely ported to Backdrop yet?

**Comment by Graham-72** [comment]
Is the further work on porting flags something we need to get Forum fully working or can we proceed with settings held in database?

**Comment by jenlampton** [comment]
I don't think it's a blocker for the forum site, but it would be good to create an issue against flag and get it sorted sooner, rather than later. (If only to enable people like you to get a local copy working!)

**Comment by Graham-72** [comment]
> create an issue against flag

I have created an issue there and will now close this one.
