### ISSUE TITLE
Make # of forum posts in category clickable to list of topics for that category

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/forum.backdropcms.org#71]
As described in issue https://github.com/backdrop-ops/forum.backdropcms.org/issues/66, I originally had trouble figuring out how to get deeper into the forums (see more of a history of what people are talking about). One possible thing that might have helped me, was to make the # of forum posts in a category clickable. 

For me, that would be a stronger indication that I would be moving towards an actual list of forum topics. 

![cursor_and_backdrop_cms_forum___backdrop_forum](https://user-images.githubusercontent.com/3144571/50378423-a54f2800-05f7-11e9-8c03-879b207b2553.png)

**Comment by klonos** [comment]
I initially thought that this is provided by a view, but its must be something custom that comes with the Borg Forum module. @docwilmot ?

**Comment by BWPanda** [comment]
Here's a PR: https://github.com/backdrop-ops/forum.backdropcms.org/pull/119

It links the Topics column to the specific forum category, and also the Comments column to the specific topic (because, why not?).

**Comment by BWPanda** [comment]
Here's what the PR does:

![image](https://user-images.githubusercontent.com/2385329/124381135-5c8c8580-dcb0-11eb-8f95-112b145ff604.png)

![image](https://user-images.githubusercontent.com/2385329/124381149-74640980-dcb0-11eb-8984-cc03b4f6d35c.png)
