### ISSUE TITLE
"Last Comment" is 1969 on all forum categories

### ISSUE THREAD

**Issue by laryn** [backdrop-ops/forum.backdropcms.org#78]
![Screen Shot 2019-05-09 at 10 07 16 AM](https://user-images.githubusercontent.com/871421/57464401-473b7e00-7242-11e9-8b6f-a428f00e486f.jpg)

**Comment by laryn** [comment]
Everyone was very talkative on New Year's Eve that year.

**Comment by hosef** [comment]
That is the date of the UNIX timestamp '0'. Is it possible that something got messed up and set a bunch of timestamps to 0 in the database?

**Comment by jenlampton** [comment]
I didn't see a PR, but the change seemed to fix the problem locally, so I've committed it and pushed it to the forum site: https://forum.backdropcms.org/

**Comment by jenlampton** [comment]
closing.
