### ISSUE TITLE
Unable to create new forum topic on new server

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/forum.backdropcms.org#79]
`Fatal error: Cannot make static method EntityInterface::entityType() non static in class Flagging in flag/includes/flag.entity.inc ox line 0`

I think this may be a bug in flag that only appears on php 7.

See https://github.com/backdrop-contrib/flag/issues/14

**Comment by docwilmot** [comment]
See Gitter chat https://gitter.im/backdrop/backdrop-issues?at=5ce256c6ecdf942b4c13296a

**Comment by jenlampton** [comment]
Please copy/paste anything relevant from gitter chat into the issue queue so we can read it all in the same place. 

I have pushed a fix to the forum site. Closing this issue.
