### ISSUE TITLE
Unable to post on the forum.

### ISSUE THREAD

**Issue by korontari** [backdrop-ops/forum.backdropcms.org#80]
I was trying to start a new forum topic (in 'How-to and Troubleshooting) but was unable to do that. I am constantly receiving the following error message:

Fatal error: Cannot make static method EntityInterface::entityType() non static in class Flagging in /home/forum/repo/www/modules/contrib/flag/includes/flag.entity.inc on line 0

**Comment by korontari** [comment]
Somehow I managed to make a post on a forum today. What has changed is that I used Opera VPN to access the forum.

**Comment by stpaultim** [comment]
Going to close this issue since @korontari seems to have gotten into forum and no one else has reported this problem. 

If you are having this problem, please reopen and provide additional details.
