### ISSUE TITLE
Add a list of OWN draft posts to the user profile (near conversations)

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/forum.backdropcms.org#82]
A draft posts view would prevent this problem:

> my forum posting attempt was made on May 29th. Even now, it still
has not appeared and does not show in my conversation list under my profile.
Yet if I go straight to the URL that I recorded in my notes at the time
I posted it, forum.backdropcms.org/forum/problem-rules-module-breaks-site-backdrop-1130 it is there.

**Comment by docwilmot** [comment]
Or disable drafts altogether. Never met a forum site that allows you to store drafts.

**Comment by jenlampton** [comment]
That's definitely easier :)
