### ISSUE TITLE
Node version 6.10 is not supported

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/forum.backdropcms.org#84]
When cloning this repo and running `lando start`, I get the following error message:

> Error: node version 6.10 is not supported

**Comment by serundeputy** [comment]
@BWPanda good call; lando no longer supports node v6.

PR: https://github.com/backdrop-ops/forum.backdropcms.org/pull/85

**Comment by jenlampton** [comment]
Looks like the PR wasn't properly linked to this issue... so closing manually :)
