### ISSUE TITLE
Allow users to edit their comments

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/forum.backdropcms.org#87]
Was there an intentional decision at any point to not allow users to edit their comments? 

I am unable to edit my comments (I can because I have admin privileges, but regular users can't). 

I'm used to being able to edit my comments on Github and sometimes I write part of a reply to someone, save it, and then go back to edit the rest but I can't. 

I think it should be acceptable to allow users to edit comments. 

Maybe this was just an accident. I feel like I used to be able to edit comments. We do allow users to edit their original post/question.

**Comment by klonos** [comment]
I agree 👍 ...I find being able to save/edit my comments valuable.

**Comment by stpaultim** [comment]
@jenlampton - Authenticated users already have permission to edit their comments on forum posts. But, there is no edit button. 

![How_do_I_make_a_private_website____Backdrop_Forum](https://user-images.githubusercontent.com/3144571/61572052-2ec7bb00-aa5e-11e9-91fb-7dfb040c3ef6.png)

Is there something else going on here?

**Comment by jenlampton** [comment]
I remember editing comments being weird. We may have to manually add the edit link in via preprocess.

**Comment by stpaultim** [comment]
I need to have a conversation with you about how I can help develop for the forums. I guess, I would need a database dump if I want to work locally and create a PR. How is that handled for forums.backdropcms.org?

**Comment by jenlampton** [comment]
sanitize?

**Comment by stpaultim** [comment]
It would seem that the problem is with Backdrop Core. Apparently, we don't ever provide an edit button for comments. 
https://github.com/backdrop/backdrop-issues/issues/3948

**Comment by jenlampton** [comment]
Yeah, I remember that being super weird about Drupal since the olden days.

**Comment by stpaultim** [comment]
Yeah. There was a core bug that prevented the "edit" comments button from displaying. It was fixed and 1.13.3 and as of today, I can edit my comments. 

https://github.com/backdrop/backdrop-issues/issues/3948
