### ISSUE TITLE
Better handling of comment title word splitting

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/forum.backdropcms.org#89]
The forum turned "won't" into "won" in the headline of this approved answer. This break very much changes the meaning of the post. 

I don't have a solution in mind and am not sure if there is a good answer, but am passing along this reported issue:
https://forum.backdropcms.org/comment/1225#comment-1225

![Backdrop_CMS_and_Drupal_8___Backdrop_Forum](https://user-images.githubusercontent.com/3144571/63237265-dd4e4f80-c206-11e9-9cf8-da9391499a7d.png)

**Comment by BWPanda** [comment]
Hmmm, sounds like it either thinks that an apostrophe is the end or a word, or it's trimming to a set character limit rather than a word limit...

Either way, I think an ellipsis should be added, as well as fixing this, to indicate that it has been trimmed.

**Comment by BWPanda** [comment]
It seems that this has since been fixed - comments no longer show titles. Will close, but if this comes up again we can re-open.
