### ISSUE TITLE
Add search block to homepage

### ISSUE THREAD

**Issue by BWPanda** [backdrop-ops/forum.backdropcms.org#90]
In https://github.com/backdrop-ops/forum.backdropcms.org/issues/58 @jenlampton said:

> A search block has been added at the top right of most pages :)

Unfortunately, none of those pages are the homepage. So when going to the forum and wanting to search for something, you can't. And it's not obvious to click on another page in order to see the search block.

I recommend adding the search block to the homepage, or at the very least a link (icon?) to the search page: https://forum.backdropcms.org/search/node

- - - - - - 
PR - https://github.com/backdrop-ops/forum.backdropcms.org/pull/99

**Comment by jenlampton** [comment]
Doh, whopsie :(

**Comment by alanmels** [comment]
Just to track the fate of this issue.

<img width="682" alt="Screen Shot 2019-10-26 at 4 24 40 PM" src="https://user-images.githubusercontent.com/56604405/67620213-2f19e400-f80d-11e9-8a5f-900b0fb9bac5.png">

**Comment by stpaultim** [comment]
I'm surprised I hadn't opened an issue on this earlier, I run into this all the time and find it frustration. Thanks @BWPanda for opening the issue. 

For the last year, I keep intending to take a week and focus on fixing issues with the forum. Hopefully, I can get to this sometime soon.

**Comment by stpaultim** [comment]
I'm going to take a stab at this issue.

**Comment by stpaultim** [comment]
OK. Basic task was pretty easy, but I managed to dig myself into a deep git hole and it took hours to get out. 

:-(

https://github.com/backdrop-ops/forum.backdropcms.org/pull/99

This PR moves two existing blocks from "top" region to "content" region and replaces them with search block. The search blocks is bigger than on other pages and centered. 

It has a label. Also added "hidden" labels to other search blocks on other layouts. 

There is a small change to css that makes the top region a little smaller to take up less space.

![Backdrop_CMS_Forum___Backdrop_Forum](https://user-images.githubusercontent.com/3144571/69020881-a7db0e80-097b-11ea-89ec-bcf25bad8101.png)

**Comment by BWPanda** [comment]
For small forms like this with only one field, I think placeholder text looks better than a field label. That or using the Compact Forms module to move the field label into the field itself.

**Comment by stpaultim** [comment]
@BWPanda - Thanks for that. Your right. This looks better. 

![Backdrop_CMS_Forum___Backdrop_Forum](https://user-images.githubusercontent.com/3144571/69027507-c6013880-0994-11ea-85f8-794b358593bd.png)

**Comment by stpaultim** [comment]
Does this look like the best config options? @BWPanda 

![Profile___Backdrop_Forum](https://user-images.githubusercontent.com/3144571/69027730-88e97600-0995-11ea-9cf2-c7480ae50f2e.png)

**Comment by BWPanda** [comment]
I'm not very knowledgeable with accessibility stuff, but I'd say the new placeholder and settings look good.

**Comment by jenlampton** [comment]
@stpaultim the PR looks great! 

> This PR moves two existing blocks from "top" region to "content" region and replaces them with search block.

Hm, why were the two more important blocks moved? Was it a design problem?

> For small forms like this with only one field, I think placeholder text looks better than a field label.

OOh, good idea. There should be placeholder text on all forms where the label is invisible for sighted readers. Thanks for fixing that too :)

I'm going to merge the PR, put the two home page blocks back, and see if I can see the problem you ran into :)

**Comment by stpaultim** [comment]
> Hm, why were the two more important blocks moved? Was it a design problem?

The top region is used for breadcrumbs and search exclusively on all other pages. 
Adding the search block to that region would have 1) departed from the design on other pages 2) added a little more theming to the PR. My goal was the simplest possible PR that looked good. 

This solutions was easy and seemed to look pretty good. 

Alternatives:

1. add another region for the search block - above the page title.
2. Find a new space on the page for the search block on front page
3. Do the extra theming/css changes to make the search block fit in the top region with everything.

None of these would be too hard and I'm happy to put more work into this if you think it would help. 

My problems yesterday were exclusively GIT and config workflow related. I have that figured out.

Here is what happens with all three blocks in the top region, without ANY additional theming.

![Backdrop_CMS_Forum___Backdrop_Forum](https://user-images.githubusercontent.com/3144571/69080815-46aa4e00-0a02-11ea-9edc-d90c7936df1f.png)

**Comment by stpaultim** [comment]
I could see a design that leaves all three in this block, but centers search bar between page title and extra text (search centered and right below Backdrop CMS Forum). That would not be hard.

**Comment by jenlampton** [comment]
> Find a new space on the page for the search block on front page

I'm giving it ago right above the list of categories...  not sure this is better, but will post a screenshot in a sec. 

I don't want it above or between the two more important blocks because I want the first things people to know about this site when they get here are 1) this is a forum and 2) this is how we behave. After that, they can search :)

**Comment by stpaultim** [comment]
Sounds good. I don't have strong feelings about the placement, beyond keeping it towards the top of the page.

**Comment by jenlampton** [comment]
What about something like this? 
<img width="1486" alt="Screen Shot 2019-11-18 at 11 07 03 AM" src="https://user-images.githubusercontent.com/397895/69081780-96cde400-09f3-11ea-9909-1aee4f464d90.png">

**Comment by jenlampton** [comment]
We're live! https://forum.backdropcms.org/
If anyone has any design suggestions on how to improve this, as I'm sure there are many, please open a new ticket :)

**Comment by jenlampton** [comment]
Also thank you @stpaultim for all your work on this issue and PR!
